### ISSUE TITLE
[Question]: Operate as cluster with leadership election and failover

### ISSUE THREAD

**Issue by sptrakesh** [Remi-Coulom/joedb#8]
Hello,

Just some thoughts floating in my mind at present, but had some questions about running joedb as embedded database with a service that provides the following:

* Use Raft to elect leader in cluster
* Write to any node in cluster
    *  Lookup leader
    *  Write to leader
    *  Notify all clients to pull
* Read against any node, should be up to date, eventual consistency is good enough.
* If leader failed, use Raft to elect new leader.
    * Can other clients pull from the new leader without issues? 

Do you think there will be issues with that basic workflow?

Thanks
Rakesh

**Comment by Remi-Coulom** [comment]
Hi Rakesh,

Thanks for your interest in joedb.

If I understand correctly, you wish to manage a situation where there is not only one fixed server machine: if for some reason the main server fails, then the rest of the machines will choose one of them to host the new server.

I feel it should work, but some caution is necessary:
 - Not all clients may be in sync at the time when a new leader is elected. If some clients managed to pull from the old leader, and some failed, then some clients may be ahead of the others. If this is the case, then the new leader should be chosen among those who have the most recent checkpoint.
 - A similar situation may occur if the leader fails while a client is holding a write lock. If you don't wish to lose what the locking client was trying to write, then only this client can become the new leader.

If a joedb client connects to a server, and the client database is ahead of the server, then the client can push the local changes to the server. So it may not be strictly necessary to elect the new leader among the clients that have the most recent checkpoint. But for this to work, you'd have to make really sure that no client starts writing to the new leader before everyone has connected and synchronized to it. Otherwise, there is a risk of creating a conflict, and there is no way to resolve a divergent history in joedb.
